### PR TITLE
Support all the bootloader versions, minor adjustments

### PR DESCRIPTION
**Pull request by salvogiangri**
Signed-off-by: Salvo Giangreco \<giangrecosalvo9@gmail.com\>

### CODE REVIEW

**Comment by Fede2782** [comment]
Thanks, you very much for this. I have just one questions about the board "SRPWC21B001" flag. Why use this instead of the one provided in default recovery img. That's just a curiosity of mine

**Comment by salvogiangri** [comment]
I saw it commented out and thought this was the one your device uses considering the previous one is the A54 one

**Comment by Fede2782** [comment]
> I saw it commented out and thought this was the one your device uses considering the previous one is the A54 one 

Yes, yes. I was asking for the last number because stock has 4 and you suggested 1. Maybe is the hw revision, but i'm not sure. Have a good day!

**Comment by salvogiangri** [comment]
That's the RP value. The fw you extracted the stock image from is probably on rev 4, so I just set the board value to rev 1 just in case

**Comment by Fede2782** [comment]
> That's the RP value. The fw you extracted the stock image from is probably on rev 4, so I just set the board value to rev 1 just in case

Ah, ok. Still really thanks.

**Pull request merged**
